name: Query BSI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get-query-bsi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get BSI data from botapi
      run: python query_bot_bsi.py
      env:
        SECRET_ID: ${{ secrets.SECRET_ID }}
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload csv to wiki
      uses: kai-tub/external-repo-sync-action@v1
      with:
          include-patterns: "*.csv"
      env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}